language: python
python:
 - "2.7"
before_install:
 - cd Proyecto_Merka
# command to install dependencies
install:
 - pip install -r requirements.txt

# command to run tests para django python
script:
 - python manage.py test
